notmuch: fix compilation error when using hcache
The error is this:

In file included from imap.c:28:0:
../mx.h:73:56: error: unknown type name ‘header_cache_t’
make[2]: *** [imap.o] Error 1

The offender commit was:

commit cc497cf32588bb080fe39dfb7a37965e92f3c01b
Author: Karel Zak <kzak@redhat.com>
Date:   Wed Dec 14 14:07:58 2011 +0100

    notmuch: consolidate msg sync code

     - add mh_sync_mailbox_message() to sync just one message
     - add msg->commited_path to save info about the final message path
       (will be used keep notmuch DB up to date)

    Signed-off-by: Karel Zak <kzak@redhat.com>

The fix consist in including hcache.h when hchace is enabled.

Signed-off-by: Víctor Manuel Jáquez Leal <vjaquez@igalia.com>